### ISSUE TITLE
Put real text in dashboard API section

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#144]
Currently lorem ipsum. Not awesome. The section doesn't per se have to be copy about the API. We can even ixnay it but I think the dashboard could benefit from some text about the lab, as its de facto homepage.

**Comment by jcahail** [comment]
I suggest the following: 
"We created Azavea's Climate API in order to give you easy access to the NEX-GDDP data without the hassle of having to download and wrangle a NetCDF dataset. With each query, you can choose from over 1,000 U.S. locations, either of the two most commonly used RCPs, 22 indicators of temperature and precipitation, and whichever timescale you would like.

To get started with the API, please review the documentation here{link to: https://docs.climate.azavea.com/}."

**Comment by fungjj92** [comment]
"and whichever timescale you would like." is a little unclear to me

Suggest:
"anywhere between 1950-2100."
