### ISSUE TITLE
Add clarifying text to login page

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#155]
Stating that the login account is the Climate API one created at https://app.climate.azavea.com/accounts/register/

It's not super clear what account users should sign in with.

**Comment by jcahail** [comment]
Several lines below the "Create an Account" link, I suggest: "If you have already registered your email address and created a password in order to access Azavea's Climate API, please enter that information above."

Add the following text to the left of "Reset your Password" link: "If you already registered, but do not know your password please..." [I'd also suggest "Reset" be changed to "reset", in order to have it read as a complete sentence, but I'll defer to others on that if it looks terrible.]

**Comment by fungjj92** [comment]
I can do this since I'm already changing text elsewhere, if you haven't already started this @CloudNiner

**Comment by CloudNiner** [comment]
Go for it, I have not.

**Comment by fungjj92** [comment]
<img width="397" alt="screen shot 2017-07-12 at 3 28 39 pm" src="https://user-images.githubusercontent.com/10568752/28136212-dfad8ce8-6716-11e7-8286-1a6cc6808277.png">

Hmm too much text looked muddled on the page. How's this
