### ISSUE TITLE
No data returned for select charts

### ISSUE THREAD

**Issue by dboyer** [azavea/climate-change-lab#288]
Tested on production in Chrome on a Macbook

1. Created a project with Chicago as the location, RCP 8.5 scenario, LOCA dataset, all models selected
2. Selected "Extreme Cold Events"
3. Count is 0.00 for all years
4. Selected "Extreme Heat Events"
5. Count is also 0.00 for all years

Content is returned for other Temperature charts.

**Comment by CloudNiner** [comment]
These indicators use historic data, so this is due to missing the calculated historical norms for LOCA data, which is encapsulated by:
- azavea/climate-change-api#713
- azavea/climate-change-api#714
- azavea/climate-change-api#715

This prompted a meeting to discuss which of the above issues to address and we'll make it a priority to fix the root cause in the following sprint.
