### ISSUE TITLE
Project creation fails

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#340]
Attempted to create a Lab project for Denton, TX (a Temperate subscriber) and project creation failed. No errors displayed.

![image](https://user-images.githubusercontent.com/24727081/53253780-05158e00-3690-11e9-8115-bc39b6a1500d.png)

**Comment by ddohler** [comment]
After rerunning `./manage.py import_regions` a number of times, this issue is resolved for nearly all cities. However, cities in Hawaii, Alaska, and the Northern Mariana Islands still have no region because they are outside the lower 48 states (see https://github.com/azavea/climate-change-api/issues/408).
