### ISSUE TITLE
Adding a single chart re-queries for all data

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#47]
Adding a chart to the list should only query the API for data for the added chart.

Currently it re-queries and reloads all charts.

**Comment by CloudNiner** [comment]
Consider refactoring ChartComponent to handle its own data, rather that receiving it from ChartsComponent

**Comment by fungjj92** [comment]
So that sounds totally sensible to me and I support it however I tried my hand at it and it's tricky.

Because there are some situations where we want to requery all of the charts, i.e. changing the dropdowns, and not, i.e. add/remove chart. If the data is queried at the chart level that also means there is not a unified place to signal global requerying. Though now that I think of it, it may be as easy as feeding the global vars as inputs through to chart level and relying on input change detection. 

In this vain, I think chart removal will be handled the same since chartList is still maintained in the same place (chart service). See #66.

**Comment by flibbertigibbet** [comment]
The chart service should be able to handle the change fine. Re-querying for all should be a simple matter of adding a convenience function to the chart service to re-query for each. As there are no data dependencies across charts, there is no reason for us to delay processing until all chart queries return as we do now, except that we return a single, monolithic data object instead of one for each chart.
