### ISSUE TITLE
Deploy app via jenkins

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#52]
Setup a s3 bucket to host

**Comment by hectcastro** [comment]
It would be great to have the AWS resources captured in Terraform. Probably not a perfect fit, but [azavea-data-hub](https://github.com/azavea/azavea-data-hub/tree/master/deployment/terraform) has a Terraform 0.7 compatible setup for CloudFront with a S3 bucket origin. May need to tweak it so that it is a S3 website origin instead.
